### ISSUE TITLE
Move off RawGit CDN by October of 2019

### ISSUE THREAD

**Issue by ericcarraway** [MakeWeirdMusic/art#1]
MWM uses RawGit to serve assets directly from this repository.

Example: `http://cdn.rawgit.com/MakeWeirdMusic/art/master/PATH/TO/ASSET`

RawGit is being shut down, so it is necessary to migrate to a different CDN before October 2019. https://rawgit.com

![screenshot 2019-06-13 at 4 17 30 PM](https://user-images.githubusercontent.com/6632454/59468069-cea67f00-8df6-11e9-9131-9f5a704c48e6.png)

**Comment by MakeWeirdMusic** [comment]
I have converted the URLs to use jsDelivr. Thanks so much @ericcarraway! https://github.com/MakeWeirdMusic/makeweirdmusic.github.io/commit/1add4cdc17978f280ea94d73b08106183cf8de71
